services:
  - type: web
    name: tableau-data-reporter
    env: python
    region: ohio
    buildCommand: pip install -r requirements.txt && bash setup_static.sh
    startCommand: >-
      python -c "import os, sqlite3; os.makedirs('data', exist_ok=True); 
      conn = sqlite3.connect('data/app.db'); 
      cursor = conn.cursor(); 
      cursor.execute('CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT UNIQUE NOT NULL, password TEXT NOT NULL, role TEXT NOT NULL, permission_type TEXT NOT NULL, organization_id INTEGER NOT NULL, organization_name TEXT NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)'); 
      cursor.execute('CREATE TABLE IF NOT EXISTS organizations (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT UNIQUE NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)'); 
      cursor.execute('SELECT id FROM organizations WHERE id = 1'); 
      if not cursor.fetchone(): cursor.execute('INSERT INTO organizations (id, name) VALUES (1, \"Default Organization\")'); 
      conn.commit(); conn.close(); print('Database initialized');" &&
      gunicorn --workers 1 --threads 8 --timeout 180 --bind 0.0.0.0:$PORT --log-level debug "app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: FLASK_DEBUG
        value: "true"
      - key: FLASK_ENV
        value: "development"
      - key: FLASK_APP
        value: "app.py"
      - key: STATIC_FOLDER
        value: "/opt/render/project/src/frontend/build"
      - key: STATIC_URL_PATH
        value: "/static_files"
      - key: SMTP_SERVER
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SENDER_EMAIL
        sync: false
      - key: SENDER_PASSWORD
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_WHATSAPP_NUMBER
        sync: false
      - key: BASE_URL
        sync: false
      - key: RENDER
        value: true
      - key: RENDER_EXTERNAL_URL
        fromService:
          type: web
          name: tableau-data-reporter
          property: url
    disk:
      name: data
      mountPath: /opt/render/project/src/data
      sizeGB: 1
    healthCheckPath: /health
    autoDeploy: true 