services:
  - type: web
    name: tableau-data-reporter
    env: python
    region: ohio
    buildCommand: |
      echo "Checking all files in directory:"
      ls -la
      echo "Installing minimal dependencies..."
      pip install flask==2.0.1 gunicorn==20.1.0
    startCommand: gunicorn minimal_app:app --bind 0.0.0.0:$PORT --log-level debug
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_APP
        value: minimal_app.py
      - key: FLASK_ENV
        value: production
      - key: RENDER
        value: true
      - key: PYTHONUNBUFFERED
        value: true
    disk:
      name: data
      mountPath: /opt/render/project/src/data
      sizeGB: 1 