services:
  - type: web
    name: tableau-data-reporter
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run tableau_streamlit_app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SMTP_SERVER
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SENDER_EMAIL
        sync: false
      - key: SENDER_PASSWORD
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_WHATSAPP_NUMBER
        sync: false
      - key: BASE_URL
        sync: false
    autoDeploy: true 